---
splunk_admin_username: "{{ lookup('community.general.onepassword', 'Splunk Cluster', field='username', vault='homelab', username=op_email, subdomain=op_domain, secret_key=op_key, master_password=op_password) }}"
splunk_admin_password: "{{ lookup('community.general.onepassword', 'Splunk Cluster', field='password', vault='homelab', username=op_email, subdomain=op_domain, secret_key=op_key, master_password=op_password) }}"

splunk_package_url_full: https://nas.balmerfamilyfarm.com:9000/public/splunk/splunk-8.1.2-545206cc9f70-Linux-x86_64.tgz
splunk_package_url_uf: https://nas.balmerfamilyfarm.com:9000/public/splunk/splunkforwarder-8.1.2-545206cc9f70-Linux-x86_64.tgz

splunk_configure_secret: true
splunk_secret_text: "{{ lookup('community.general.onepassword', 'Splunk Cluster', field='splunk_secret', vault='homelab', username=op_email, subdomain=op_domain, secret_key=op_key, master_password=op_password) }}"
